all: zad1 zad2 zad3

zad1: z1.cpp
	g++ z1.cpp -o z1
	./z1
	gnuplot z1.plt

zad2: z2.cpp
	g++ z2.cpp -o z2
	./z2
	gnuplot z2.plt
	
zad3: z3.cpp
	g++ z3.cpp -o z3
	./z3
	gnuplot z3.plt
	
clean:
	rm *.txt *.png z1 z2 z3
